### ISSUE TITLE
Direct access to $_GET and $_POST is not allowed

### ISSUE THREAD

**Issue by danmarsden** [Celumproject/moodle-mod_domoscio#10]
You must use optional/required_param functions to obtain data from $_GET/$_POST with appropriate validation such as PARAM_INT or PARAM_TEXT etc.

one example (there may be others)
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/quiz.php#L70

**Comment by fearcraftor** [comment]
Fixed
https://github.com/Celumproject/moodle-mod_domoscio/commit/a6d8d199eb93fdc12ebb808d3d2da281e13e4925

Florent

Domoscio

**Comment by danmarsden** [comment]
There still appears to be a lot of other areas in your code that make direct calls to $_POST/$_GET - please work on this further before resubmitting.

**Comment by fearcraftor** [comment]
We fixed this security issue https://github.com/Celumproject/moodle-mod_domoscio/blob/8a7498fa47dd00665455e81ec14d6548965f4146/domoscio/results.php
There's no direct use of $_POST anymore, and we added sesskey checking to tests forms submitting

**Comment by fearcraftor** [comment]
Tell me if you see something that would still doesn't fit security requirements before we resubmit

**Comment by danmarsden** [comment]
It looks like newer commits since your last update in the plugins db have removed the remaining $_POST/$_GET but there are still issues with your in-line SQL injecting variables directly into the SQL statement rather than using correct moodle syntax.

**Comment by fearcraftor** [comment]
I'm currently working on it ;)
